vich_uploader:
    db_driver: orm

    mappings:
        recettes:
            uri_prefix: /img/recettes
            upload_destination: '%kernel.project_dir%/public/img/recettes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 
        categories:
            uri_prefix: /img/categories
            upload_destination: '%kernel.project_dir%/public/img/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        ingredients:
            uri_prefix: /img/ingredients
            upload_destination: '%kernel.project_dir%/public/img/ingredients'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer